### ISSUE TITLE
Fix licence string

### ISSUE THREAD

**Issue by tripu** [w3c/hanuman#2]
npm complains about the licence string in `package.json` (`W3C Software License`) not being valid:

```
$ npm install
npm WARN Hanuman@0.2.0 license should be a valid SPDX license expression
```

Do we have our W3C licence(s) available as [SPDX](https://spdx.org/)? Register them (if such thing is possible) to comply with the [`spdx` Node.js package](https://www.npmjs.com/package/spdx).

Pinging @wseltzer as she probably knows about this :)

**Comment by wseltzer** [comment]
I've never heard of SPDX. If you think it's something we should do, I'll look into it.

**Comment by tripu** [comment]
(@plehegar: sorry, I looked into this before realising you had assigned yourself to the issue&hellip; :)

**Comment by plehegar** [comment]
sounds good. if this issue lingers and needs a quick fix, it's fine to use MIT license.
